# Imagen base
FROM node:20

# Carpeta de trabajo
WORKDIR /app

# Copiamos package.json y package-lock.json primero (para cacheo)
COPY package*.json ./

# Instalamos dependencias del proyecto
RUN npm install

# Instalamos Angular CLI globalmente
RUN npm install -g @angular/cli

# Copiamos todo el código del proyecto Angular
COPY . .

# Exponemos el puerto
EXPOSE 4200

# Arrancamos el servidor Angular
CMD ["ng", "serve", "--host", "0.0.0.0", "--configuration", "docker"]
